language: node_js
node_js:
  - 0.10.25

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  #- karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  #- karma start config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
  #- karma start config/karma.conf.js --no-auto-watch --single-run --reporters=coverage --browsers=Firefox
  - karma start config/karma-travis.conf.js --browsers=Firefox --single-run

after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
